# Generated by Django 3.2.4 on 2021-09-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_map_intergration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_office_type',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_office_type2',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
