# Generated by Django 3.2.4 on 2021-09-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210905_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='office_type2_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
