# Generated by Django 3.2.4 on 2021-09-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='our_way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=15)),
                ('Second_heading', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Our_Way',
            },
        ),
        migrations.CreateModel(
            name='ways_Describe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way_title', models.CharField(max_length=15)),
                ('way_description', models.TextField(max_length=80)),
                ('way_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Ways_Describe',
            },
        ),
    ]
