# Generated by Django 3.2.4 on 2021-09-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_way',
            name='Second_heading',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='our_way',
            name='heading',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='our_way',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
