# Generated by Django 3.2.4 on 2021-09-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourway', '0002_auto_20210905_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ways_describe',
            name='way_description',
            field=models.TextField(max_length=200),
        ),
    ]
