# Generated by Django 3.2.4 on 2021-09-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourway', '0003_alter_ways_describe_way_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ways_describe',
            old_name='way_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ways_describe',
            old_name='way_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='ways_describe',
            old_name='way_title',
            new_name='title',
        ),
    ]
