# Generated by Django 3.2.4 on 2023-02-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empowering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empower', models.CharField(max_length=50)),
                ('empower_description', models.TextField()),
                ('up_left', models.ImageField(blank=True, null=True, upload_to='')),
                ('up_right', models.ImageField(blank=True, null=True, upload_to='')),
                ('down_left', models.ImageField(blank=True, null=True, upload_to='')),
                ('down_right', models.ImageField(blank=True, null=True, upload_to='')),
                ('empower_background', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Empowering Section',
            },
        ),
        migrations.CreateModel(
            name='meet_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_team', models.CharField(max_length=50)),
                ('meet_description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Meet Our Team',
            },
        ),
        migrations.CreateModel(
            name='meet_team_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_team_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('post', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Meet Team Image',
            },
        ),
        migrations.CreateModel(
            name='ourstory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ourstory', models.CharField(max_length=50)),
                ('ourstory_description', models.TextField()),
                ('ourstory_lastdescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storypage_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('storypage_title', models.CharField(max_length=50)),
                ('storypage_description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'story Homepage',
            },
        ),
        migrations.CreateModel(
            name='story_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=50)),
                ('story_description', models.TextField()),
                ('story_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Story with Description',
            },
        ),
        migrations.CreateModel(
            name='team_describe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_team', models.CharField(max_length=50)),
                ('team_description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Team Description',
            },
        ),
        migrations.CreateModel(
            name='team_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Team Image',
            },
        ),
    ]
