# Generated by Django 3.2.4 on 2023-01-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('booking_title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'booking',
            },
        ),
    ]
