# Generated by Django 3.2.4 on 2023-01-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'bookinglist',
            },
        ),
    ]
