# Generated by Django 3.2.4 on 2023-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_list',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_list',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
