# Generated by Django 3.2.4 on 2023-01-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20230130_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_list',
            name='date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='booking_list',
            name='time',
            field=models.CharField(max_length=2),
        ),
    ]
