# Generated by Django 3.2.4 on 2023-02-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20230204_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketball_list',
            options={'verbose_name_plural': 'basketballlist'},
        ),
        migrations.AlterModelOptions(
            name='cricshal',
            options={'verbose_name_plural': 'cricshal'},
        ),
        migrations.AlterModelOptions(
            name='cricshal_list',
            options={'verbose_name_plural': 'cricshallist'},
        ),
    ]
