# Generated by Django 3.2.4 on 2023-02-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_booking_booking_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketball_list',
            name='phone',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking_list',
            name='phone',
            field=models.CharField(default=2, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cricshal_list',
            name='phone',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
