# Generated by Django 3.2.4 on 2023-02-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20230205_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_list',
            name='booking_description',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_description',
            field=models.TextField(null=True),
        ),
    ]
