# Generated by Django 3.2.4 on 2023-02-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_booking_list_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_list',
            old_name='Book',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
