# Generated by Django 3.2.4 on 2023-02-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_list',
            name='book',
        ),
    ]
