# Generated by Django 3.2.4 on 2023-02-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_remove_booking_list_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_token',
            fields=[
                ('token', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
