# Generated by Django 3.2.4 on 2023-02-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_alter_discount_token_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount_token',
            name='discount_token',
            field=models.IntegerField(default=56),
            preserve_default=False,
        ),
    ]
