# Generated by Django 3.2.4 on 2023-02-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_discount_token_discount_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount_token',
            name='discount_token',
        ),
        migrations.AlterField(
            model_name='discount_token',
            name='token',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
