# Generated by Django 3.2.4 on 2023-02-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20230206_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_list',
            name='book',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
            preserve_default=False,
        ),
    ]
