# Generated by Django 3.2.4 on 2023-02-07 06:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_remove_booking_list_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_list',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
            preserve_default=False,
        ),
    ]
