# Generated by Django 3.2.4 on 2023-02-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_auto_20230207_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_list',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.DeleteModel(
            name='foreign',
        ),
    ]
