# Generated by Django 3.2.4 on 2023-02-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_booking_booking_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_list',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking'),
        ),
    ]
