# Generated by Django 3.2.4 on 2023-02-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0054_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount_token',
            name='token',
        ),
        migrations.AddField(
            model_name='discount_token',
            name='discount_token',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount_token',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
