# Generated by Django 3.2.4 on 2023-02-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0055_auto_20230210_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount_token',
            old_name='discount_token',
            new_name='token',
        ),
    ]
