# Generated by Django 3.2.4 on 2023-02-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0056_rename_discount_token_discount_token_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='discount_token',
        ),
    ]
