# Generated by Django 3.2.4 on 2023-02-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0057_delete_discount_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
            ],
        ),
    ]
