# Generated by Django 3.2.4 on 2023-02-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0058_discount_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='discount_token',
        ),
    ]
