# Generated by Django 3.2.4 on 2023-02-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0059_auto_20230210_0150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='token',
        ),
    ]
