# Generated by Django 3.2.4 on 2023-02-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basketball',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('booking_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('booking_title', models.CharField(max_length=50)),
                ('booking_description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'basketball',
            },
        ),
        migrations.CreateModel(
            name='basketball_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=12)),
                ('time', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'basketballlist',
            },
        ),
    ]
