# Generated by Django 3.2.4 on 2023-02-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_description', models.TextField(max_length=70)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.ImageField(blank=True, null=True, upload_to='')),
                ('slider_title', models.CharField(max_length=50)),
                ('landing_description1', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'home_slider',
            },
        ),
        migrations.CreateModel(
            name='home_feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=15)),
                ('feature_type1', models.CharField(max_length=15)),
                ('feature_type2', models.CharField(max_length=15)),
                ('feature_type3', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'home_feature',
            },
        ),
        migrations.CreateModel(
            name='knitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knitting_title', models.CharField(max_length=25)),
                ('knitting_description', models.TextField()),
                ('knitting_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('knitting_background', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'knitting',
            },
        ),
        migrations.CreateModel(
            name='leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('leader_name', models.CharField(max_length=25)),
                ('leader_position', models.CharField(max_length=25)),
                ('facebook_link', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedln_link', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'leadership',
            },
        ),
        migrations.CreateModel(
            name='notified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('notified_bg', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'notified',
            },
        ),
        migrations.CreateModel(
            name='testomonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'testomonial',
            },
        ),
        migrations.CreateModel(
            name='why_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whyus_title', models.CharField(max_length=10)),
                ('whyus_description', models.TextField()),
                ('whyus_bg', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'why_us',
            },
        ),
    ]
